# Generated by Django 6.0.3 on 2026-05-06 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('carat', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('seller_phone', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'db_table': 'gem_listings',
            },
        ),
    ]
