# Generated by Django 6.0.3 on 2026-05-01 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_user_alter_profile_profile_id'),
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemlisting',
            name='owner',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
