# Generated by Django 6.0.3 on 2026-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemlisting',
            name='color',
            field=models.TextField(blank=True, default='Blue', null=True),
        ),
        migrations.AddField(
            model_name='gemlisting',
            name='variety',
            field=models.TextField(blank=True, default='Variety', null=True),
        ),
    ]
