# Generated by Django 6.0.3 on 2026-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_gemlisting_color_gemlisting_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemlisting',
            name='weight',
            field=models.FloatField(blank=True, default=4.5, null=True),
        ),
    ]
