# Generated by Django 6.0.3 on 2026-05-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_gemlisting_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemlisting',
            name='weight',
        ),
    ]
