# Generated by Django 6.0.3 on 2026-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0004_remove_gemlisting_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemlisting',
            name='certificate_url',
            field=models.TextField(blank=True, default=' https://www.orimi.com/pdf-test.pdf', null=True),
        ),
    ]
