# Generated by Django 6.0.3 on 2026-04-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.UUIDField()),
                ('title', models.TextField()),
                ('company_info', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('logo_color', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.UUIDField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('expected_salary', models.TextField(blank=True, null=True)),
                ('cv_url', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
