# Generated by Django 6.0.3 on 2026-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
