# Generated by Django 6.0.3 on 2026-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_application_applicant_id_alter_job_employer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="expected_salary",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
