# Generated by Django 6.0.3 on 2026-05-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', to_field='profile_id'),
        ),
    ]
