# Generated by Django 6.0.3 on 2026-05-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0003_alter_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo_color',
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
