# Generated by Django 6.0.3 on 2026-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
