# Generated by Django 6.0.3 on 2026-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_salary_job_max_salary_job_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
