# Generated by Django 6.0.3 on 2026-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
